version: '3.8'
services:
  api:
    build: ./api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:pass@db:5432/rehearsals
    depends_on:
      - db
    ports:
      - '4000:4000'
  client:
    build: ./client
    ports:
      - '3000:3000'
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rehearsals
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
